# Generated by Django 3.1a1 on 2020-07-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('arxiv_id', models.CharField(help_text="Arxiv qualifier like '2000.01234'.", max_length=20)),
                ('authors', models.TextField(help_text='Authors of the reference as comma seperated list.')),
                ('title', models.CharField(help_text='Title of the publication.', max_length=256)),
                ('journal', models.CharField(blank=True, help_text='Journal qualifier of the publication.', max_length=256, null=True)),
                ('url', models.URLField(blank=True, help_text='Link to access the publication, e.g., inspirehep.net link.', null=True)),
                ('misc', models.JSONField(blank=True, help_text='Additional optional information.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
