# Generated by Django 3.1a1 on 2020-07-07 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='url',
        ),
        migrations.AddField(
            model_name='publication',
            name='inspirehep_id',
            field=models.IntegerField(default=0, help_text='Insprie HEP id (inspirehep.net/literature/{id}).', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='preprint_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 7, 9, 20, 30, 236698, tzinfo=utc), help_text='Date preprint got uploaded.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='arxiv_id',
            field=models.CharField(help_text="Arxiv qualifier like '2000.01234'.", max_length=20, unique=True),
        ),
    ]
