# Generated by Django 3.1a1 on 2020-07-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20200707_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='arxiv_id',
            field=models.CharField(blank=True, help_text="Arxiv qualifier like '2000.01234'.", max_length=20, null=True),
        ),
    ]
