# Generated by Django 3.1a1 on 2020-07-07 09:59

from django.db import migrations
import strops.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofieldoperator',
            name='matrix1',
            field=strops.utils.fields.SympyField(encoder='non-commutative-expression', help_text='Term representing the operator. For example $\\gamma_5$'),
        ),
        migrations.AlterUniqueTogether(
            name='twofieldoperator',
            unique_together={('field1', 'matrix1', 'field2')},
        ),
    ]
