# Generated by Django 3.1a1 on 2020-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansionscheme',
            name='description',
            field=models.TextField(help_text='What does this scheme represent?', null=True),
        ),
    ]
