# Generated by Django 3.1rc1 on 2020-07-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_auto_20200727_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansionorder',
            name='relation',
            field=models.ForeignKey(help_text='The relation between operators at different scales.', on_delete=django.db.models.deletion.CASCADE, related_name='expansion', to='schemes.operatorrelation'),
        ),
    ]
