# Generated by Django 3.1rc1 on 2020-07-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_auto_20200728_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansionscheme',
            name='name',
            field=models.CharField(help_text='Name of the expansion scheme.', max_length=256, unique=True),
        ),
    ]
