SECRET_KEY: "0i%2jg3v%^q=&g8pr_kd*so_@gpe@z0f9xxfi&g@d(e9m@@8g^"
PROJECT_APPS:
    - strops.app.operators
    - strops.app.parameters
    - strops.app.schemes
    - strops.app.references
ALLOWED_HOSTS: []
DEBUG: True
