# Generated by Django 3.1a1 on 2020-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20200707_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='preprint_date',
            field=models.DateField(blank=True, help_text='Date preprint got uploaded.', null=True),
        ),
    ]
