# Generated by Django 3.0.7 on 2020-06-24 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DOF',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('kind', models.CharField(help_text="Kind of operator like 'quark'  or 'nucleon'.", max_length=256)),
                ('name', models.CharField(help_text="Descriptive name like 'up quark' or 'proton'.", max_length=256)),
                ('label', models.CharField(help_text="Which version of d.o.f., e.g., specifying flavor ('up') or strong isospin ('proton').", max_length=256)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kind', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('name', models.CharField(max_length=256)),
                ('n_dofs', models.PositiveIntegerField()),
                ('expression', models.TextField(help_text='Fully qualified term discribing operator including creation and annihilation operators.', unique=True)),
                ('kind', models.CharField(choices=[('s', 'Scalar'), ('v', 'Vector'), ('ps', 'Pseudo Scalar'), ('pv', 'Pseudo Vector'), ('t', 'Tensor'), ('pt', 'Pseudo Tensor')], help_text='Which kind of spin interactions describe this operator?', max_length=2)),
                ('parity', models.IntegerField()),
                ('time', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('dof', models.ManyToManyField(to='operators.DOF')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('arxiv_id', models.CharField(max_length=20)),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorRelation',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('factor', models.TextField()),
                ('scheme', models.CharField(max_length=256)),
                ('references', models.ManyToManyField(to='operators.Reference')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_for', to='operators.Operator')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_of', to='operators.Operator')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
