# Generated by Django 3.1rc1 on 2020-07-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20200707_1645'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='Publication specifying the parameter.', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.publication'),
        ),
    ]
