# Generated by Django 3.1rc1 on 2020-07-29 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0004_auto_20200707_1645'),
        ('parameters', '0003_auto_20200729_1303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('name', 'symbol')},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value',
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('mean', models.FloatField(help_text='Mean value of parameter.')),
                ('sdev', models.FloatField(blank=True, help_text='Standard deviation of parameter.', null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of parameter.', max_length=10, null=True)),
                ('parameter', models.ForeignKey(help_text='The abstract instance of the parameter.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='parameters.parameter')),
                ('reference', models.ForeignKey(blank=True, help_text='Publication specifying the parameter.', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.publication')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parameter', 'reference')},
            },
        ),
    ]
